global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'pigdns'
    scrape_interval: 5s
    static_configs:
      - targets: ['pigdns:8080']