services:
  pigdns:
    restart: always
    image: ghcr.io/ferama/pigdns:main
    container_name: pigdns
    # port mappings doesn't work with ipv6
    network_mode: host
    volumes:
      - ./data:/data
      - ./default.yaml:/etc/pigdns.yaml 
