services:
  pigdns:
    image: ghcr.io/ferama/pigdns:main
    container_name: pigdns
    ports:
      - "0.0.0.0:53:53/udp"
    volumes:
      - data:/var/lib/pigdns
      - ./default.yaml:/etc/pigdns.yaml 
volumes:
  data:
