services:
  pigdns:
    restart: unless-stopped
    image: ghcr.io/ferama/pigdns:main
    container_name: pigdns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./data:/data
      - ./default.yaml:/etc/pigdns.yaml 
