services:
  pigdns:
    restart: unless-stopped
    image: ghcr.io/ferama/pigdns:main
    container_name: pigdns
    logging:
      driver: json-file
      options:
        max-size: "512m"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - pigdns-storage:/var/lib/pigdns
      - ./pigdns/whitelist:/etc/pigdns/whitelist
      - ./pigdns/pigdns.yaml:/etc/pigdns/pigdns.yaml
  
  node-exporter:
    restart: unless-stopped
    image: prom/node-exporter:latest
    container_name: node-exporter
    logging:
      driver: json-file
      options:
        max-size: "8m"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  prometheus:
    restart: unless-stopped
    image: prom/prometheus
    container_name: prometheus
    logging:
      driver: json-file
      options:
        max-size: "8m"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    restart: unless-stopped
    image: ghcr.io/ferama/grafana:v10.2.0
    container_name: grafana
    logging:
      driver: json-file
      options:
        max-size: "8m"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana


volumes:
  grafana-storage:
  pigdns-storage:
